chat/urls.py
from django.urls import path
from .views import ChatView, SendTextView, GetTextView

app_name = 'chat'
urlpatterns = [
    path('<int:pk>/', ChatView.as_view(), name='room'),
    path('text/', SendTextView.as_view(), name='send_text'),
    path('get_text/', GetTextView.as_view(), name='get_text'),
]

facetagram/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from facetagram import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('authenticate:login')), name='home'),
    path('authenticate/', include('authenticate.urls'), name='authenticate'),
    path('posts/', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('chat/', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from .views import ProfileDetailView, ProfileListView, ProfileUpdateView, FriendRequest, \
                    AcceptFriendRequestView, JSONSearchProfile, JSONGetNotifications

app_name = 'profiles'
urlpatterns = [
    path('', ProfileListView.as_view(), name='list'),
    path('<int:pk>/', ProfileDetailView.as_view(), name='detail'),
    path('<int:pk>/update', ProfileUpdateView.as_view(), name='update'),
    path('friend_request/', FriendRequest.as_view(), name='friend_request'),
    path('create_friendship/', AcceptFriendRequestView.as_view(), name='create_friendship'),
    path('search/', JSONSearchProfile.as_view(), name='search'),
    path('get_notifications/', JSONGetNotifications.as_view(), name='get_notifications')
]

chat/models.py
from django.db import models
from django.conf import settings


class Room(models.Model):
    room_id = models.IntegerField(primary_key=True)
    date_created = models.DateTimeField(auto_now_add=True)


class Message(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    text = models.TextField(max_length=5000, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

chat/views.py
import json

from django.views.generic.base import View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from .models import Room, Message


class ChatView(LoginRequiredMixin, ListView, SingleObjectMixin):
    template_name = 'chat/chat.html'
    context_object_name = 'messages'
    paginate_by = 30

    def get(self, request, *args, **kwargs):
        user = self.request.user
        room_ids = [user.generate_room_id(friend.pk) for friend in user.friends.only("pk", "username", "avatar")] 
        self.object = self.get_object(queryset=Room.objects.filter(room_id__in=room_ids))
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.message_set.order_by("-date_created")
    
    def get_context_data(self, **kwargs):
        context = super(ChatView, self).get_context_data(**kwargs)
        user = self.request.user
        for friend in user.friends.all():
            if self.object.pk == user.generate_room_id(friend.pk):
                context['friend'] = friend
                break
        return context


class SendTextView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request):
        body = json.loads(request.body)
        room_id = body['room_id']
        text = body['text']
        if not text or text.isspace():
            return JsonResponse({})
        room = get_object_or_404(Room, room_id=room_id)
        Message.objects.create(room=room, user=request.user, text=text)
        return JsonResponse({})


class GetTextView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request):
        body = json.loads(request.body)
        room = get_object_or_404(Room, room_id=body['room_id'])
        message_id = body['message']
        if message_id == -1:
            qs = Message.objects.filter(room=room)
        else:
            date = Message.objects.get(id=message_id).date_created
            qs = Message.objects.filter(date_created__gt=date, room=room)
        return JsonResponse(list(qs.values()), safe=False)

templates/chat/chat.html
{% extends 'base.html' %}

{% block title %}Chat{% endblock %}

{% load static %}

{% block extra_headers %}
<style>
    .messages, .message{
        transform: rotate(180deg);
        transform-origin: center center;
        direction: rtl;
    }
</style>
{% endblock %}

{% block content %}
<div class="chat m-auto mt-3 bg-white rounded-3 shadow d-flex flex-column">
    <div class="infinite-container py-3 w-100 h-100 messages d-flex flex-column px-3">
        {% for message in messages %}
        {% if message.user == request.user %}
        <div class="align-self-end my-1 infinite-item message d-flex flex-nowrap justify-content-start" id="{{message.id}}">
            <a href="{% url 'profiles:detail' request.user.id %}">
                <img src="{{ request.user.get_avatar_url }}" alt="avatar" class="avatar">
            </a>
            <p class="text bg-primary text-white py-1 px-2 fw-bold rounded-3">{{message.text}}</p>
        </div>
        {% else %}
        <div class="align-self-start my-1 infinite-item message d-flex flex-nowrap justify-content-end" id="{{message.id}}">
            <p class="text bg-secondary text-white py-1 px-2 fw-bold rounded-3">{{message.text}}</p>
            <a href="{% url 'profiles:detail' friend.id %}" class="">
                <img src="{{ friend.get_avatar_url }}" alt="avatar" class="avatar">
            </a>
        </div>
        {% endif %}
        {% endfor %}
        <div class="pagination">
            {% if page_obj.has_next %}
            <a class="infinite-more-link" href="?page={{page_obj.next_page_number}}"></a>
            {% endif %}
        </div>   
    </div>
    <div class="input-group w-100">
        <input type="text" class="form-control" placeholder="Type..." id="text" autofocus autocomplete="off">
        <button type="submit" class="btn btn-outline-primary bg-white input-group-text fas fa-arrow-alt-circle-right" id="send">
        </button>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        sendText = () => {
            text = document.getElementById('text');
            let xhr = new XMLHttpRequest();
            xhr.open('POST', "{% url 'chat:send_text' %}", true);
            xhr.setRequestHeader('X-CSRFToken', '{{csrf_token}}');
            xhr.setRequestHeader('Content-Type', 'application/json');
            xhr.send(JSON.stringify({ room_id: '{{object.room_id}}', text: text.value }));
            text.value = '';
        }
        document.getElementById('send').addEventListener('click', sendText);
        document.getElementById('text').addEventListener('keydown', (event) => {
            if (event.key == 'Enter') sendText();
        });
        request = setInterval(() => {
            messages = document.getElementsByClassName('message');
            if (messages.length > 0){
                latest_message = messages[0].id
            }else{
                latest_message = -1
            }
            let xhr = new XMLHttpRequest();
            xhr.open('POST', "{% url 'chat:get_text' %}", true);
            xhr.setRequestHeader('X-CSRFToken', '{{csrf_token}}');
            xhr.setRequestHeader('Content-Type', 'application/json');
            xhr.send(JSON.stringify({ room_id: '{{object.room_id}}', message: latest_message }));
            xhr.onreadystatechange = () => {
                if (xhr.readyState != 4) return;
                if (xhr.status == 200) {
                    const data = JSON.parse(xhr.responseText);
                    if (Object.keys(data).length != 0){
                        for (i in data){
                            messages = document.querySelector('.messages')
                            if (data[i].user_id == '{{request.user.id}}'){
                                messages.innerHTML =  `<div class="align-self-end my-1 infinite-item message d-flex flex-nowrap justify-content-start" id="${data[i].id}">
                                    <a href="{% url 'profiles:detail' request.user.id %}">
                                        <img src="{{ request.user.get_avatar_url }}" alt="avatar" class="avatar">
                                    </a>
                                    <p class="text bg-primary text-white py-1 px-2 fw-bold rounded-3"></p>
                                </div>` + messages.innerHTML
                            }else{
                                messages.innerHTML =  `<div class="align-self-start my-1 infinite-item message d-flex flex-nowrap justify-content-end" id="${data[i].id}">
                                    <p class="text bg-secondary text-white py-1 px-2 fw-bold rounded-3"></p>
                                    <a href="{% url 'profiles:detail' friend.id %}" class="">
                                        <img src="{{ friend.get_avatar_url }}" alt="avatar" class="avatar">
                                    </a>
                                </div>` + messages.innerHTML
                            }
                            messages.firstChild
                            .querySelector('p')
                            .textContent = data[i].text
                        }
                    }
                }
            }
        }, 2500);
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            offset: 'bottom-in-view',
            onBeforePageLoad: () => {
            },
            onAfterPageLoad: () => {
                document.getElementById('send').addEventListener('click', sendText);
                document.getElementById('text').addEventListener('keydown', (event) => {
                    if (event.key == 'Enter') sendText();
                });
            },
        });
    });
</script>
{% endblock %}