authenticate/urls.py
from django.urls import path
from .views import RegisterView, CustomLoginView
from django.contrib.auth.views import LogoutView
from facetagram import settings

app_name = 'authenticate'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout')
]

chat/urls.py
from django.urls import path
from .views import ChatView, SendTextView, GetTextView

app_name = 'chat'
urlpatterns = [
    path('<int:pk>/', ChatView.as_view(), name='room'),
    path('text/', SendTextView.as_view(), name='send_text'),
    path('get_text/', GetTextView.as_view(), name='get_text'),
]

facetagram/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from facetagram import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('authenticate:login')), name='home'),
    path('authenticate/', include('authenticate.urls'), name='authenticate'),
    path('posts/', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('chat/', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import CreatePostView, DeletePostView, RatePostView, \
    PostListView, PostView, RateCommentView

app_name = 'posts'
urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', CreatePostView.as_view(), name='create'),
    path('delete/', DeletePostView.as_view(), name='delete'),
    path('rate/', RatePostView.as_view(), name='rate_post'),
    path('comment/rate/', RateCommentView.as_view(), name='like_comment'),
    path('<pk>/', PostView.as_view(), name='detail'),
]

profiles/urls.py
from django.urls import path
from .views import ProfileDetailView, ProfileListView, ProfileUpdateView, FriendRequest, \
                    AcceptFriendRequestView, JSONSearchProfile, JSONGetNotifications

app_name = 'profiles'
urlpatterns = [
    path('', ProfileListView.as_view(), name='list'),
    path('<int:pk>/', ProfileDetailView.as_view(), name='detail'),
    path('<int:pk>/update', ProfileUpdateView.as_view(), name='update'),
    path('friend_request/', FriendRequest.as_view(), name='friend_request'),
    path('create_friendship/', AcceptFriendRequestView.as_view(), name='create_friendship'),
    path('search/', JSONSearchProfile.as_view(), name='search'),
    path('get_notifications/', JSONGetNotifications.as_view(), name='get_notifications')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{{ description|truncatechars:256 }}">
    <title>{% block title %} {%  endblock %}</title>    
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"><script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% if request.user.is_authenticated %}
    <link rel="stylesheet" href="{% static 'css/custom/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom/nav.css' %}">
    <script src="{% static 'js/custom/variables.js' %}"></script>
    <script src="{% static 'js/custom/nav.js' %}"></script>
    {% endif %}
    {% block extra_headers %}{% endblock %}
    {% block js %}{% endblock %}
</head>

<body>
    {% if request.user.is_authenticated %}
    <nav class="navbar navbar-expand-sm navbar-primary bg-white position-sticky top-0 py-0">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">facetagram</a>
            <button class="navbar-toggler btn btn-outline-primary" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fas fa-bars icon-lg"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav flex-row justify-content-evenly justify-content-sm-end align-items-center w-100">
                    <li class="nav-item profiles p-1 my-1 me-1">
                        <a href="{% url 'profiles:list' %}" title="Find users" class="fas fa-search nav-link p-1 icon-lg"
                        title="Find new friends"></a>
                    </li>
                    <li class="nav-item friends p-1 my-1 me-1">
                        <a href="{% url 'profiles:list' %}?filter=friends" title="Friends" class="fas fa-user-friends nav-link p-1 icon-lg" title="My friends"></a>
                    </li>
                    <li class="nav-item home p-1 my-1 me-1">
                        <a href="{% url 'posts:list' %}" title="Home Page" class="fas fa-home nav-link p-1 icon-lg"></a>
                    </li>
                    <li class="nav-item dropstart p-1 me-1">
                        <a class="nav-link p-0" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false"><img src="{{request.user.get_avatar_url}}" alt="avatar"
                        class="i-avatar"></a>
                        <ul class="dropdown-menu position-absolute" aria-labelledby="userDropdown" style="z-index: 1;">
                            <li>
                                <a href="{% url 'profiles:detail' request.user.pk %}"
                                class="dropdown-item text-primary">Profile</a>
                            </li>
                            <li>
                                <a href="{% url 'profiles:update' request.user.pk %}" class="dropdown-item text-primary">Update Profile</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a href="{% url 'authenticate:logout' %}" class="dropdown-item text-danger">Log Out</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item p-1 me-2">
                        <a class="nav-link fas fa-bell icon-lg p-0 position-relative" data-bs-toggle="offcanvas" href="#notifications" role="button" aria-controls="notifications">
                            <span class="d-none position-absolute text-white bg-danger top-0 end-0 px-1 notification-count" style="border-radius: 50%; font-size: .7em;"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="offcanvas offcanvas-end" tabindex="-1" id="notifications" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasExampleLabel">Notifications</h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body m-auto">
            <div class="toast-container">
                {% for notification in notifications %}
                <div class="toast show toast{{notification.id}}" role="alert" aria-live="assertive" aria-atomic="true" id="{{notification.id}}">
                    <div class="toast-header">
                        <a href="{% url 'profiles:detail' notification.sender.id %}" class="user" id="{{notification.sender.id}}">
                            <img src="{{notification.sender.get_avatar_url}}" class="rounded me-2 avatar" alt="avatar">
                        </a>
                        <strong class="me-auto">{{notification.sender.username}}</strong>
                        <small class="text-muted">{{notification.date_created}}</small>
                    </div>
                    <div class="toast-body">
                        Friend request
                        <div class="mt-3 pt-3 border-top d-flex justify-content-evenly">
                            <button class="btn btn-primary w-50 accept" id="{{notification.id}}">Accept</button>
                            <button class="btn btn-secondary w-50 ms-3 deny" id="{{notification.id}}">Deny</button>
                        </div>
                    </div>
                </div>
                {% empty %}
                <h5 class="text-muted mt-3 mx-auto">No notifications</h5>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
    
    {% block content %}
    {% endblock %}
</body>

</html>

templates/create_post.html
<nav class="position-fixed bottom-0 vw-100 shadow bg-white d-flex justify-content-center align-items-center">
    <div class="big-plus">
        <button data-bs-toggle="modal" title="Add Post" data-bs-target="#add-post" class="btn"><span class="fas fa-plus big-plus fa-4x"></span></button>
    </div>
</nav>
<form method="POST" action="{% url 'posts:create' %}"  class="modal fade" id="add-post" tabindex="-1" aria-labelledby="add-post" aria-hidden="true" enctype="multipart/form-data">{% csrf_token  %}
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content mx-3">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <figure id="post-figure" class="figure post-image d-none align-content-center justify-content-center m-auto">
                    <img alt="post" id="post-img" class="figure-img img-fluid mx-auto">
                </figure>
                <div class="mb-3">
                    <label class="fw-bold" for="image" class="col-form-label">Select Image:</label>
                    <input type="file" class="form-control" name="image" accept="img/*" id="post-input">
                </div>
                <div class="mb-3">
                    <label class="fw-bold" for="location" class="col-form-label">Location:</label>
                    <input type="text" class="form-control" name="location" maxlength="50">
                </div>
                <div class="mb-3">
                    <label class="fw-bold" for="description" class="col-form-label">Description:</label>
                    <textarea class="form-control" name="description"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Post</button>
            </div>
        </div>
    </div>
</form>