chat/urls.py
from django.urls import path
from .views import ChatView, SendTextView, GetTextView

app_name = 'chat'
urlpatterns = [
    path('<int:pk>/', ChatView.as_view(), name='room'),
    path('text/', SendTextView.as_view(), name='send_text'),
    path('get_text/', GetTextView.as_view(), name='get_text'),
]

facetagram/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from facetagram import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('authenticate:login')), name='home'),
    path('authenticate/', include('authenticate.urls'), name='authenticate'),
    path('posts/', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('chat/', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import CreatePostView, DeletePostView, RatePostView, \
    PostListView, PostView, RateCommentView

app_name = 'posts'
urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', CreatePostView.as_view(), name='create'),
    path('delete/', DeletePostView.as_view(), name='delete'),
    path('rate/', RatePostView.as_view(), name='rate_post'),
    path('comment/rate/', RateCommentView.as_view(), name='like_comment'),
    path('<pk>/', PostView.as_view(), name='detail'),
]

profiles/urls.py
from django.urls import path
from .views import ProfileDetailView, ProfileListView, ProfileUpdateView, FriendRequest, \
                    AcceptFriendRequestView, JSONSearchProfile, JSONGetNotifications

app_name = 'profiles'
urlpatterns = [
    path('', ProfileListView.as_view(), name='list'),
    path('<int:pk>/', ProfileDetailView.as_view(), name='detail'),
    path('<int:pk>/update', ProfileUpdateView.as_view(), name='update'),
    path('friend_request/', FriendRequest.as_view(), name='friend_request'),
    path('create_friendship/', AcceptFriendRequestView.as_view(), name='create_friendship'),
    path('search/', JSONSearchProfile.as_view(), name='search'),
    path('get_notifications/', JSONGetNotifications.as_view(), name='get_notifications')
]

profiles/models.py
import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.templatetags.static import static
from django.urls import reverse

from helpers.image_compression import get_compressed_image_content


GENDER = (
    ('Female', 'Female'),
    ('Male', 'Male'),
    ('Others', 'Others'),
)


class User(AbstractUser):
    email = models.EmailField(unique=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=6, choices=GENDER, null=True, blank=True)
    biography = models.TextField(max_length=10000, null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars', null=True, blank=True)
    is_private = models.BooleanField(default=False, blank=True)
    friends = models.ManyToManyField("self", blank=True)

    def get_age(self):
        today = datetime.date.today()
        return today.year - self.date_of_birth.year - ((today.month, today.day)
                                                       < (self.date_of_birth.month, self.date_of_birth.day))

    def save(self, *args, **kwargs):
        if self.avatar:
            self.avatar = get_compressed_image_content(self.avatar, [256, 256])
        super().save(*args, **kwargs)

    def get_avatar_url(self):
        if not self.avatar:
            return static('img/default_avatar.png')
        return self.avatar.url

    def generate_room_id(self, user_id) -> int:
        users = sorted([self.id, user_id])
        return int('0'.join([str(users[0]), str(users[1])]))


    @staticmethod
    def get_absolute_url():
        return reverse('posts:list')


class Notification(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                               related_query_name='sender', related_name='sender')
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                 related_query_name='receiver', related_name='receiver')
    date_created = models.DateTimeField(auto_now_add=True)

profiles/forms.py
from django import forms
from .models import User


class UpdateProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date'}))
    biography = forms.CharField(widget=forms.Textarea(), required=False)

    class Meta:
        model = User
        fields = ('username',
                  'email',
                  'first_name',
                  'last_name',
                  'date_of_birth',
                  'avatar',
                  'country',
                  'gender',
                  'biography',
                  'is_private')

profiles/views.py
import json

from django.views.generic.base import View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.db.models.expressions import Exists, OuterRef, Q, Value, F
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.templatetags.static import static

from .forms import UpdateProfileForm
from .models import User, Notification
from posts.models import LikePost
from chat.models import Room


class ProfileDetailView(LoginRequiredMixin, ListView, SingleObjectMixin):
    template_name = "profiles/profiles_detail.html"
    context_object_name = 'posts'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        user = self.request.user
        is_friend = Exists(user.friends.filter(pk=OuterRef("pk")))
        is_waiting = Exists(Notification.objects.filter(sender=user, receiver_id=OuterRef("pk")))
        self.object = self.get_object(queryset=User.objects.annotate(is_friend=is_friend, is_waiting=is_waiting))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = self.object
        return context

    def get_queryset(self):
        user = self.request.user
        is_liked = Exists(LikePost.objects.filter(user=user, post_id=OuterRef("id"), value=1))
        is_disliked = Exists(LikePost.objects.filter(user=user, post_id=OuterRef("id"), value=-1))
        return self.object.post_set.annotate(is_liked=is_liked, is_disliked=is_disliked)


class ProfileListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'profiles/profiles_list.html'
    context_object_name = 'profiles'
    paginate_by = 20

    def get_queryset(self):
        user = self.request.user
        search = self.request.GET.get('search') or ''
        filter = self.request.GET.get("filter")
        is_friend = Exists(user.friends.filter(pk=OuterRef("pk")))
        is_waiting = Exists(Notification.objects.filter(sender=user, receiver_id=OuterRef("pk")))
        if filter == "friends":
            return user.friends.filter(username__icontains=search)\
                .only('username', 'pk', 'avatar', 'id')\
                .annotate(is_friend=is_friend, is_waiting=is_waiting)
        return User.objects.filter(username__icontains=search)\
            .exclude(pk=user.pk)\
            .only('username', 'pk', 'avatar', 'id')\
            .annotate(is_friend=is_friend, is_waiting=is_waiting)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'profiles/profiles_update.html'
    form_class = UpdateProfileForm
    context_object_name = 'user'

    def get_queryset(self):
        return User.objects.filter(pk=self.request.user.pk)


class FriendRequest(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request):
        body = json.loads(request.body)
        user = request.user
        if body["profile_id"] == user.pk:
            raise PermissionDenied
        friend = get_object_or_404(User, id=body.get('profile_id'))
        value = body.get('value')
        is_friend = user.friends.filter(pk=friend.pk)
        notification_exists = Notification.objects.filter(
            Q(sender=user, receiver=friend) | Q(sender=friend, receiver=user)
        ).exists()
        if value == 'add' and is_friend:
            return JsonResponse({})
        elif value == 'add' and not (notification_exists or is_friend):
            Notification.objects.create(sender=user, receiver=friend)
        elif value == 'cancel' and notification_exists and not is_friend:
            Notification.objects.get(sender=user, receiver=friend).delete()
        elif value == 'deny' and notification_exists and not is_friend:
            Notification.objects.get(sender=friend, receiver=user).delete()
        elif value == 'remove' and is_friend:
            user.friends.remove(friend)
        return JsonResponse({})


class AcceptFriendRequestView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request):
        body = json.loads(request.body)
        user = request.user
        if body["user"] == user.pk:
            raise PermissionDenied
        friend = get_object_or_404(User, id=body['user'])
        room_id = user.generate_room_id(friend.pk)
        if user.friends.filter(pk=friend.pk).exists():
            return JsonResponse({})
        if not Room.objects.filter(room_id=room_id).exists():
            Room.objects.create(room_id=room_id)
        user.friends.add(friend)
        notification = get_object_or_404(Notification, id=body['notification'])
        notification.delete()
        return JsonResponse({})


class JSONSearchProfile(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request):
        user = self.request.user
        body = json.loads(request.body)
        search = body.get("search")
        friends = body.get("friends")
        users = User.objects
        if friends:
            users = user.friends
        qs = users.filter(username__istartswith=search).exclude(pk=user.pk)
        context = list(qs.values("id", "username"))
        return JsonResponse(context, safe=False)


class JSONGetNotifications(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request):
        user = self.request.user
        body = json.loads(request.body)
        qs = user.receiver.filter(id__gt=body["last_notification_id"]).annotate(
            sender_username=F("sender__username"),
            sender_avatar=F("sender__avatar"),
            default_avatar=Value(static("img/default_avatar.png"))
        )
        context = list(qs.values())
        return JsonResponse(context, safe=False)

templates/profiles/profiles_detail.html
{% extends 'base.html' %}
{% load static %}
{% load functions %}

{% block title %}Profile Detail{% endblock %}

{% block extra_headers %}
{% if not request.user == profile %}     
<script src="{% static 'js/custom/friend_request.js' %}"></script>
{% endif %}
<script src="{% static 'js/custom/rate.js' %}"></script>
<script src="{% static 'js/custom/delete_post.js' %}"></script>
<script src="{% static 'js/custom/create_post.js' %}"></script>
{% endblock %}

{% block content %}

{% if profile == request.user %}
{% include 'create_post.html' %}
{% endif %}

<section class="profile-detail w-100 container-sm px-3 py-2 bg-white shadow">
    <div class="row p-3 pb-0">
        <div class="col-4 d-flex justify-content-center align-items-center">
            <figure class="figure">
                <img src="{{profile.get_avatar_url}}" alt="avatar" class="figure-img avatar-lg img-fluid">
            </figure>
        </div>
        <div class="col-8 d-flex flex-column justify-content-center">
            <div class="d-flex">
                <label class="fw-bold me-2" for="username">Username:</label>
                <p>{{profile.username}}</p>
            </div>
            {% if profile.get_full_name %}
            <div class="d-flex">
                <label class="fw-bold me-2" for="Full Name">Name:</label>
                <p>{{profile.get_full_name}}</p>
            </div>
            {% endif %}
            
            {% if profile.date_of_birth %}
            <div class="d-flex">
                <label class="fw-bold me-2" for="date_of_birth">Birthday:</label>
                <p>{{user.date_of_birth}}</p>
            </div>
            {% endif %}
            
            {% if profile.country %}
            <div class="d-flex">
                <label class="fw-bold me-2" for="country">Country:</label>
                <p>{{profile.country}}</p>
            </div>
            {% endif %}
            <div class="d-flex">
                <label class="fw-bold me-2" for="friends">Friends:</label>
                <p>{{profile.friends.count}}</p>
            </div>
        </div>
    </div>
    <div class="row p-3 pt-0">
        <p>{{profile.biography}}</p>
    </div>
    {% if not request.user == profile %}
    <div class="d-flex justify-content-end p-2">
        {% if profile.is_friend %}
        {% generate_room_id request.user.pk profile.pk as room_id %}
        <a href="{% url 'chat:room' room_id %}" class="btn btn-primary fas fa-envelope room-link" id="link{{profile.pk}}"></a>
        <button class="btn btn-danger fas fa-user-minus remove request ms-1" id="{{profile.pk}}"></button>
        {% elif profile.is_waiting %}
        <button class="btn btn-warning fas fa-user-minus cancel request" id="{{profile.pk}}"></button>
        {% else %}
        <button class="btn btn-primary fas fa-user-plus add request" id="{{profile.pk}}"></button>
        {% endif %}
    </div>
    {% endif %}
</section>
<section class="d-flex flex-column mx-auto infinite-container mt-2 w-100 d-flex align-items-center" style="margin-bottom: 7em;">
    {% if profile == request.user  or request.user in profile.friends.all or not profile.is_private %}
    {% for post in posts %}
    <div class="card post bg-white m-0 py-2 my-1 infinite-item shadow" id="{{post.id}}">
        <div class="card-header d-flex align-items-center">
            <a class="px-1" href="{% url 'profiles:detail' post.user.pk %}">
                <img class="avatar-sm fs-3" src="{{post.user.get_avatar_url}}" alt="avatar">
            </a>
            <div class="ms-2 flex-grow-1 d-flex flex-column align-items-start justify-content-evenly">
                <a class="name m-0 link-dark text-decoration-none fw-bold" style="font-size: 1.2em;" href="{% url 'profiles:detail' post.user.pk %}">{{post.user}}</a>
                {% if post.location %}
                <p class="small col-10 mb-1 fw-light lh-1">{{post.location}}</p>
                {% else %}
                <div class="mb-2"></div>
                {% endif %}
            </div>
            {% if request.user == profile %}
            <button class="btn btn-outline-danger justify-self-end delete fas fa-trash-alt" id="{{post.id}}"></button>
            {% endif %}
        </div>
        {% if post.image %}
        <figure class="figure post-image card-img d-flex align-content-center justify-content-center m-auto" onclick="window.location='{% url 'posts:detail' post.pk %}'">
            <img src="{{post.image.url}}" alt="post" class="figure-img img-fluid mx-auto">
        </figure>
        {% endif %}
        <div class="card-body pb-1 pt-0">
            {% if post.description %}
            <p class="card-text fw-bold px-3 pt-1 my-1" onclick="window.location='{% url 'posts:detail' post.pk %}'">{{post.description}}</p>
            {% endif %}  
            <div class="links d-flex justify-content-between mb-1 pt-0">
                <div class="thumbs d-flex align-items-center">
                    <span class="btn icon-sm {% if post.is_liked %}fas text-primary{% else %}far{% endif %} fa-thumbs-up rate like p{{post.id}}" id="{{post.id}}">{{post.get_like_count}}</span>
                    <span class="btn icon-sm {% if post.is_disliked %}fas text-danger{% else %}far{% endif %} fa-thumbs-down rate dislike p{{post.id}}" id="{{post.id}}">{{post.get_dislike_count}}</span>
                </div>
                <div>
                    <a href="{% url 'posts:detail' post.pk %}" class="btn link-dark text-decoration-none">
                        <small class="me-1 c{{post.id}} icon-sm">{{post.get_comment_count}}</small>
                        <span class="text-primary fas fa-comment-alt icon-sm"></span>
                    </a>
                </div>
            </div>   
        </div>
        <div class="card-footer text-muted text-end">
            {{post.date_created}}
        </div>
    </div>
    <div class="pagination">
        {% if page_obj.has_next %}
        <a class="infinite-more-link" href="?page={{page_obj.next_page_number}}"></a>
        {% endif %}
    </div>
    {% empty %}
    <h5 class="text-center text-muted">No posts</h5>
    {% endfor %}
    {% else %}
    <h1 class="text-primary d-flex flex-column text-center mt-3">
        <i class="fas fa-lock mb-2" style="font-size:5em;"></i>
        <label>Private</label>
    </h1>
</section>
{% endif %}
{% endblock %}

{% block js %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        {% if not request.user == profile %}     
        document.querySelector(".request").addEventListener("click", friendRequest);
        {% endif %}
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            offset: 'bottom-in-view',
            onBeforePageLoad: () => {
            },
            onAfterPageLoad: () => {
                document.querySelectorAll('.rate').forEach((rate) => {
                    rate.addEventListener('click',  sendRate);
                });  
                document.querySelectorAll('.delete').forEach((btn) => {
                    btn.addEventListener('click', deletePost);
                });
            },
        });
    });
</script>
{% endblock js %}

templates/profiles/profiles_list.html
{% extends 'base.html' %}
{% load static %}
{% load functions %}

{% block title %}Profile List{% endblock %}

{% block extra_headers %}
<script src="{% static 'js/custom/friend_request.js' %}"></script>
<script src="{% static 'js/custom/autocomplete.js' %}"></script>
<script src="{% static 'js/custom/search_profiles.js' %}"></script>
{% endblock %}
{% block content %}
<section class="container-sm w-75  mx-auto rounded-3 my-3 users">
    <form method="GET" autocomplete="off" class="d-flex justify-content-center position-sticky top-0 search bg-white border-0 border-bottom rounded-0 border-primary rounded-3 autocomplete">
        <input class="form-control border-primary text-primary border-0" type="search" placeholder="Search" aria-label="Search" name="search" value="{{request.GET.search|default_if_none:''}}" id="search">
        <button class="btn btn-outline-primary px-2 ms-1 border-0" type="submit"><i class="fas fa-search" id="search-btn"></i></button>
    </form> 
    <ul class="p-0 mt-2 infinite-container" id="profiles">
        {% for profile in profiles %}
        <li class="d-flex infinite-item flex-row align-items-center justify-content-between p-1 my-3 border-bottom">
            <h5 class="fw-bold" style="font-size: 1.25em" onclick="window.location.assign('{% url 'profiles:detail' profile.pk %}')">
                <img src="{{profile.get_avatar_url}}" alt="avatar" class="avatar-md me-1">
                {{profile.username}}
            </h5>
            <div>
                {% if profile.is_friend %}
                {% generate_room_id request.user.pk profile.pk as room_id %}
                <a href="{% url 'chat:room' room_id %}" class="btn btn-primary fas fa-envelope room-link" id="link{{profile.pk}}"></a>
                <button class="btn btn-danger fas fa-user-minus remove request" id="{{profile.pk}}"></button>
                {% elif profile.is_waiting %}
                <button class="btn btn-warning fas fa-user-minus cancel request" id="{{profile.pk}}"></button>
                {% else %}
                <button class="btn btn-primary fas fa-user-plus add request" id="{{profile.pk}}"></button>
                {% endif %}
            </div>
        </li>
        {% empty %}
        <h5 class="text-muted w-100 text-center mt-3">No users are available</h5>
        {% endfor %}    
        <div class="pagination">
            {% if page_obj.has_next %}
            <a class="infinite-more-link" href="?page={{page_obj.next_page_number}}"></a>
            {% endif %}
        </div>       
    </ul>
</section>
{% endblock %}

{% block js %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        {% if request.GET.filter == "friends" %}
        document.querySelector('.friends').classList.add('current-page');
        const friends = true
        {% else %}
        document.querySelector('.profiles').classList.add('current-page');
        const friends = false
        {% endif %}

        /* Infinite scroll */
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            offset: 'bottom-in-view',
            onBeforePageLoad: () => {
            },
            onAfterPageLoad: () => {
                document.querySelectorAll('.request').forEach(btn => btn.addEventListener('click', friendRequest));    
            },
        });
    });
</script>
{% endblock %}

templates/profiles/profiles_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}facetagram{% endblock %}

{% block extra_headers %}
<style>
    .avatar {
        border-radius: 50%;
        width: 10em;
        height: 10em;
    }
</style>
{% endblock %}

{% block content %}
<form method="POST" class="container-sm my-5" enctype="multipart/form-data"> {% csrf_token %}
    <div class="row justify-content-center flex-column flex-md-row">
        <div class="col order-1 order-md-0">
            <div class="row mb-3 flex-column align-items-center">
                <label for="username" class="label text-capitalize">username:</label>
                <div class="input-group">
                    <i class="fas fa-user text-white bg-primary input-group-text icon-sm"></i>
                    <input type="text" class="form-control" name="username"
                           value='{{form.username.value|default_if_none:""}}' maxlength="150" required
                           placeholder="Type here...">
                </div>
            </div>
            <div class="row mb-3 flex-column align-items-center">
                <label for="first_name" class="label text-capitalize">first name:</label>
                <div class="input-group">
                    <i class="fas fa-id-card text-white bg-primary input-group-text icon-sm"></i>
                    <input type="text" class="form-control" value='{{form.first_name.value|default_if_none:""}}'
                           name="first_name" maxlength="150" placeholder="Type here...">
                </div>
            </div>
            <div class="row mb-3 flex-column align-items-center">
                <label for="last_name" class="label text-capitalize">last name:</label>
                <div class="input-group">
                    <i class="fas fa-id-card text-white bg-primary input-group-text icon-sm"></i>
                    <input type="text" class="form-control" value='{{form.last_name.value|default_if_none:""}}'
                           name="last_name" maxlength="150" placeholder="Type here...">
                </div>
            </div>
            <div class="row mb-3 flex-column align-items-center">
                <label for="email" class="label text-capitalize">email address:</label>
                <div class="input-group">
                    <i class="fas fa-envelope text-white bg-primary input-group-text icon-sm"></i>
                    <input type="email" class="form-control" value='{{form.email.value|default_if_none:""}}'
                           name="email" maxlength="243" required placeholder="Type here...">
                </div>
            </div>
        </div>
        <div class="col order-0 order-md-1 mb-3 mb-md-0 me-md-5">
            <div class="row justify-content-center">
                <label for="avatar" class="label text-capitalize">Avatar:</label>
                <figure class="figure">
                    <img src="{{request.user.get_avatar_url}}" alt="avatar" class="avatar figure-img d-block mx-auto"
                         style="max-width: 13.9em;" id="avatar">
                </figure>
                <input type="file" class="form-control file-input" name="avatar" accept="img/*" style="width:50%"
                       id="avatar-input">
            </div>
        </div>
    </div>
    <div class="row mb-3 justify-content-center flex-column flex-md-row">
        <div class="col">
            <div class="row mb-3 flex-column align-items-center">
                <label for="country" class="label text-capitalize">country:</label>
                <div class="input-group">
                    <i class="fas fa-city text-white bg-primary input-group-text icon-sm"></i>
                    <input type="text" class="form-control" value='{{form.country.value|default_if_none:""}}'
                           name="country" maxlength="150" placeholder="Type here...">
                </div>
            </div>
            <div class="row mb-3 flex-column align-items-center">
                <label for="date_of_birth" class="label text-capitalize">date of birth:</label>
                <div class="input-group">
                    <i class="fas fa-birthday-cake text-white bg-primary input-group-text icon-sm"></i>
                    <input type="date" class="form-control" value='{{form.date_of_birth.value|date:"Y-m-d"}}'
                           name="date_of_birth">
                </div>
            </div>
            <div class="row mb-3 flex-column align-items-center">
                <label for="gender" class="label text-capitalize">gender:</label>
                <div class="input-group">
                    <i class="fas fa-male text-white bg-primary input-group-text icon-sm"></i>
                    <select name="gender" id="gender_id" class="form-select">
                        {% for option in form.gender %}
                        {{option}}
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="col mb-2 me-md-5">
            <label for="biography" class="label text-capitalize">biography:</label>
            <textarea name="biography" id="biography_id" cols="35" rows="8" class="form-control w-100 h-100"
                      maxlength="10000" placeholder="Type here..." style="max-height: 12em;">{{form.biography.value|default_if_none:""}}</textarea>
        </div>
    </div>
    <div class="row justify-content-between me-5 flex-wrap">
        <div class="col-3">
            <label class="label">Private:</label>
            <input type="checkbox" name="is_private" class="checkbox" {% if form.is_private.value == True %}checked{% endif %} title="When your account is private, just your friends can see your posts.">
        </div>
        <div class="btn-group col-3" role="group">
            <a class="btn btn-danger lh-lg" href="{% url 'profiles:detail' user.pk %}">Cancel</a>
            <button class="btn btn-primary px-3 lh-lg" type="submit">Save</button>
        </div>
    </div>

</form>
{% endblock %}

{% block js %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        document.getElementById('avatar-input').addEventListener('change', event => {
            document.getElementById('avatar').src = URL.createObjectURL(event.target.files[0]);
        })
    })
</script>
{% endblock %}