authenticate/urls.py
from django.urls import path
from .views import RegisterView, CustomLoginView
from django.contrib.auth.views import LogoutView
from facetagram import settings

app_name = 'authenticate'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout')
]

chat/urls.py
from django.urls import path
from .views import ChatView, SendTextView, GetTextView

app_name = 'chat'
urlpatterns = [
    path('<int:pk>/', ChatView.as_view(), name='room'),
    path('text/', SendTextView.as_view(), name='send_text'),
    path('get_text/', GetTextView.as_view(), name='get_text'),
]

facetagram/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from facetagram import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('authenticate:login')), name='home'),
    path('authenticate/', include('authenticate.urls'), name='authenticate'),
    path('posts/', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('chat/', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authenticate/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from profiles.models import User


class Clean:
    def clean_username(self): 
        username = self.cleaned_data.get('username')

        return username.lower()


class CreateUserForm(Clean, UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'email')

    


class LoginForm(Clean, AuthenticationForm):
    pass

authenticate/views.py
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView
from django.shortcuts import reverse
from django.shortcuts import redirect

from .forms import CreateUserForm, LoginForm


class RegisterView(CreateView):
    template_name = 'authenticate/register.html'
    form_class = CreateUserForm

    def get_success_url(self):
        return reverse('authenticate:login')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse("posts:list"))
        return super().dispatch(request, *args, **kwargs)


class CustomLoginView(LoginView):
    template_name = 'authenticate/login.html'
    redirect_authenticated_user = True
    form_class = LoginForm    

templates/authenticate/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/custom/register.css' %}">
<form method="POST" class="shadow rounded-3 d-flex flex-column align-items-center justify-content-center py-3 px-5 position-absolute translate-middle-x start-50">
    {% csrf_token %}
    <div class="row justify-content-center border-bottom pb-3">
        <img src="{% static 'favicon.ico' %}" alt="icon" class="icon-lg">
    </div>
    <div class="row mt-3">
        <label for="username" class="form-label ps-0">Username:</label>
        <div class="input-group has-validation">
            <span class="input-group-text far fa-user text-white bg-primary" id="username-icon"></span>
            <input type="text" class="form-control {% if form.errors %} is-invalid {% endif %}" name="username" id="username" autocomplete="username" required autofocus value='{{form.username.value|default_if_none:""}}' aria-describedby="invalid-feedback">
        </div>
    </div>
    <div class="row mt-3">
        <label for="password" class="form-label ps-0">Password:</label>
        <div class="input-group has-validation">
            <span class="input-group-text fas fa-key text-white bg-primary" id="password-icon"></span>
            <input type="password" class="form-control {% if form.errors %} is-invalid {% endif %}" id="password" name="password" required autocomplete="current-password" aria-describedby="invalid-feedback">
        </div>
    </div>
    {% if form.errors %}
    <div class="invalid-feedback d-block" id="invalid-feedback">
        {{form.errors}}
    </div>
    {% endif %}
    <div class="row my-3 {% if form.errors %}mt-0{% endif %}">
        <input type="submit" class="btn btn-primary w-100" value="Login">
    </div>
    <footer class="my-1 w-100 text-center">
        Don't have an account yet? Please <a href="{% url 'authenticate:register' %}" class="text-decoration-none">Register</a>
    </footer>
</form>
{% endblock %}

templates/authenticate/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Registration{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/custom/register.css' %}">
<form method="POST" class="shadow d-flex flex-column align-items-center justify-content-center py-3 px-5 position-absolute rounded-3 translate-middle-x start-50">
    {% csrf_token %}
    <div class="row justify-content-center border-bottom pb-3">
        <img src="{% static 'favicon.ico' %}" alt="icon" class="icon-lg">
    </div>
    <div class="row mt-3">
        <label for="email" class="form-label ps-0 mb-1">Email:</label>
        <div class="input-group has-validation">
            <span class="input-group-text far fa-envelope text-white bg-primary" id="email-icon"></span>
            <input type="email" class="form-control {% if form.errors.email %} is-invalid {% elif request.POST %} is-valid {% endif %}" id="email" name="email" autocomplete="email" value='{{form.email.value|default_if_none:""}}' aria-describedby="email-feedback email-icon" required autofocus>
            <div class="invalid-feedback" id="email-feedback">
                {{form.errors.email}}
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <label for="username" class="form-label ps-0  mb-1">Username:</label>
        <div class="input-group has-validation">
            <span class="input-group-text far fa-user text-white bg-primary" id="username-icon"></span>
            <input type="text" class="form-control {% if form.errors.username %} is-invalid {% elif request.POST %} is-valid {% endif %}" id="username" name="username" autocomplete="username" value='{{form.username.value|default_if_none:""}}' aria-describedby="username-feedback username-icon" required>
            <div class="invalid-feedback" id="username-feedback">
                {{form.errors.username}}
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <label for="password" class="form-label ps-0  mb-1">Password:</label>
        <div class="input-group has-validation">
            <span class="input-group-text fas fa-key text-white bg-primary" id="password1-icon"></span>
            <input type="password" class="form-control {% if form.errors.password %} is-invalid {% endif %}" id="password1" name="password1" autocomplete="new_password" aria-describedby="password1-feedback password1-icon" required>
            <div class="invalid-feedback" id="password1-feedback">
                {{form.errors.password}}
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <label for="password2" class="form-label ps-0  mb-1">Confirm Password:</label>
        <div class="input-group has-validation">
            <span class="input-group-text fas fa-key text-white bg-primary" id="password2-icon"></span>
            <input type="password" class="form-control {% if form.errors.password2 %} is-invalid {% endif %}" id="password2" name="password2" autocomplete="off" aria-describedby="password2-feedback password2-icon" required>
            <div class="invalid-feedback" id="password2-feedback">
                {{form.errors.password2}}
            </div>
        </div>
    </div>
    <div class="row my-3">
        <input type="submit" class="btn btn-primary w-100" value="Register">
    </div>
    <footer class="my-1 w-100 text-center">
        Already have an accaunt? Please <a href="{% url 'authenticate:login' %}" class="text-decoration-none">login</a>
    </footer>
</form>
{% endblock %}